### ISSUE TITLE
CMake error with FindOpenMP

### ISSUE THREAD

**Issue by JiaJiDuan** [ROCmSoftwarePlatform/rocWMMA#288]
I built rocwmma from source code with tag rocm-5.7.0.  
`cmake -S . -B build -G Ninja -DCMAKE_CXX_COMPILER=hipcc -DCMAKE_BUILD_TYPE=Release -DCMAKE_INSTALL_PREFIX=$ROCM_PATH -DCMAKE_PREFIX_PATH=$ROCM_PATH -DAMDGPU_TARGETS=gfx1102 -DROCWMMA_BUILD_TESTS=OFF -DROCWMMA_BUILD_SAMPLES=OFF`  
Error reported as follows:  
```
CMake Error at /usr/share/cmake-3.22/Modules/FindPackageHandleStandardArgs.cmake:230 (message):
  Could NOT find OpenMP_CXX (missing: OpenMP_CXX_FLAGS OpenMP_CXX_LIB_NAMES)
Call Stack (most recent call first):
  /usr/share/cmake-3.22/Modules/FindPackageHandleStandardArgs.cmake:594 (_FPHSA_FAILURE_MESSAGE)
  /usr/share/cmake-3.22/Modules/FindOpenMP.cmake:544 (find_package_handle_standard_args)
  CMakeLists.txt:98 (find_package)
```
Here's my question:  
1. Whether openmp in rocwmma is for cpus or gpus? What is the purpose of using openmp？
2. Do I need to compile openmp support for amdgpu and how?
3.  I compiled llvm-project and hipcc from source，It does not have OpenMP-related header files and libraries.What can I do to solve this problem？  
>
>
Looking forward to reply

**Comment by cgmillette** [comment]
Hi @JiaJiDuan ,
1. OpenMP is used for host-side validation and supporting test code.
2. No, not required
3. rocWMMA is a header library. The cmake build only creates tests and samples where required. Otherwise you can use the rocWMMA headers directly. If you are just wanting to make / install headers without tests or samples, you may omit the openmp package requirement [here](https://github.com/ROCmSoftwarePlatform/rocWMMA/blob/develop/CMakeLists.txt#L98)

**Comment by JiaJiDuan** [comment]
Hi @cgmillette ，
>
Thanks for your reply, I understand now. 
>
I will close this issue.
